#%RAML 1.0 Trait
responses:
  400:
    body:
      application/json:
        example:
          {
            "Message": "Bad Request"
          }
  401:
    body:
      application/json:
        example:
          {
            "Message":"Unautherized"
          }        
  403:
    body:
      application/json:
        example:
          {
            "Message":"Forbidden"
          }        
  500:
    body:
      application/json:
        example:
          {
            "Message":"Internal Server Error"
          }        
  503:
    body:
      application/json:
        example:
          {
            "Message":" Service unavilable"
          }